SLURM_JOBID:  11570226
SLURM_ARRAY_TASK_ID:  117
SLURM_ARRAY_JOB_ID:  11570108
2020-08-11 22:28:38.496238: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /sw/arcts/centos7/python3.6-anaconda/5.2.0/lib:/opt/slurm/lib64::
2020-08-11 22:28:38.496401: E tensorflow/stream_executor/cuda/cuda_driver.cc:313] failed call to cuInit: UNKNOWN ERROR (303)
2020-08-11 22:28:38.496422: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (gl3050.arc-ts.umich.edu): /proc/driver/nvidia/version does not exist
2020-08-11 22:28:38.496729: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2020-08-11 22:28:38.503749: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 3000000000 Hz
2020-08-11 22:28:38.503841: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5570388dbb40 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-08-11 22:28:38.503852: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
/home/smaity/.local/lib/python3.6/site-packages/numpy/core/fromnumeric.py:3335: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/home/smaity/.local/lib/python3.6/site-packages/numpy/core/_methods.py:161: RuntimeWarning: invalid value encountered in true_divide
  ret = ret.dtype.type(ret / rcount)
/home/smaity/.local/lib/python3.6/site-packages/numpy/core/_methods.py:217: RuntimeWarning: Degrees of freedom <= 0 for slice
  keepdims=keepdims)
/home/smaity/.local/lib/python3.6/site-packages/numpy/core/_methods.py:186: RuntimeWarning: invalid value encountered in true_divide
  arrmean, rcount, out=arrmean, casting='unsafe', subok=False)
/home/smaity/.local/lib/python3.6/site-packages/numpy/core/_methods.py:209: RuntimeWarning: invalid value encountered in true_divide
  ret = ret.dtype.type(ret / rcount)
(5278, 8)
['sex', 'race', 'priors_count', 'age_cat=25 to 45', 'age_cat=Greater than 45', 'age_cat=Less than 25', 'c_charge_degree=F', 'c_charge_degree=M']
sex
race


Measures for gender

Accuracy is 0.660038
Balanced accuracy is 0.654901
Gap RMS is 0.14199906474776824
Mean absolute gap is 0.13261401027976377
Max gap is 0.1833807185319204
Average odds difference is 0.132614
Equal opportunity difference is 0.183381
Statistical parity difference is 0.170813



Measures for race

Accuracy is 0.660038
Balanced accuracy is 0.654901
Gap RMS is 0.125603374354548
Mean absolute gap is 0.12223876591962453
Max gap is 0.1511159499183451
Average odds difference is 0.122239
Equal opportunity difference is 0.151116
Statistical parity difference is 0.160215
